services:
  - type: web
    name: leetcode-ai
    env: python
    plan: free

    buildCommand: |
      pip install uv
      uv sync
      python manage.py collectstatic --noinput
      uv run python manage.py migrate
      

    startCommand: uv run gunicorn leetcode_ai.wsgi:application

    envVars:
      - key: PYTHON_VERSION
        value: 3.12